version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: email_db
      POSTGRES_USER: email_user
      POSTGRES_PASSWORD: securepassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: email_app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://email_user:securepassword@db/email_db"
    ports:
      - "8000:8000"
    command: [ "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000" ]

volumes:
  postgres_data:
